[build]
  command = "npm ci && npm install typescript && npm run build && cd backend && npm ci && npm run build"
  publish = "dist"
  functions = "backend/functions"

[functions]
  external_node_modules = ["express", "socket.io", "bcrypt", "jsonwebtoken", "@supabase/supabase-js", "nodemailer"]
  node_bundler = "esbuild"
  included_files = ["backend/src/**/*", ".env"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --no-optional"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://healthcareclinic-management.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true" 