[build]
  base = "/"
  command = "npm ci && npm run build"
  publish = "dist"

[[headers]]
  for = "/assets/*"
  [headers.values]
    "Content-Type" = "application/javascript"
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    "Content-Type" = "application/javascript"
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    "Content-Type" = "text/css"
    "Cache-Control" = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --no-optional"
  VITE_API_URL = "https://healthcareclinic-management.netlify.app/.netlify/functions/api" 