[build]
  command = "npm install && npm run build"
  functions = "functions"
  publish = "public"

[functions]
  external_node_modules = ["express", "socket.io", "bcrypt", "jsonwebtoken", "@supabase/supabase-js", "nodemailer"]
  node_bundler = "esbuild"
  included_files = ["src/**/*", ".env"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5000
  framework = "#custom"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps" 