[build]
  command = "npm install && npm run build"
  functions = "functions"
  publish = "public"

[functions]
  external_node_modules = ["express", "socket.io", "bcrypt", "jsonwebtoken", "@supabase/supabase-js", "nodemailer"]
  node_bundler = "esbuild"
  included_files = ["src/**/*", ".env"]

[[redirects]]
  force = true
  from = "/.netlify/functions/api/auth/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  force = true
  from = "/.netlify/functions/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  force = true
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5000
  framework = "#custom"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --no-optional"

[[plugins]]
  package = "@netlify/plugin-functions-install-core" 